source ~/.zplug/init.zsh
source ~/.nvm/nvm.sh
source ~/bin/*

source $HOME/code/dotfiles/zsh/aliases

zplug 'mafredri/zsh-async'
zplug 'sindresorhus/pure'
zplug 'zsh-users/zsh-syntax-highlighting', defer:1
zplug 'zsh-users/zsh-completions', defer:2

zplug load

DISABLE_AUTO_UPDATE="true" 

eval "$(rbenv init - --no-rehash)"

